# Generated by Django 2.2.17 on 2020-11-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='title',
        ),
        migrations.AddField(
            model_name='customtext',
            name='jhdkhaskh',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='customtext',
            name='kjj',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
